version: '1.0'
services:
  kafka-handler:
    build: "./kafka_node"
    container_name: "kafka-handler"
    ports:
      - "5001:5001"
    volumes:
      - "./kafka_node/:/app/"
    links:
      - zookeeper-1
      - kafka-1
      - kafka-2

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      ALLOW_ANONYMOUS_LOGIN: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper: 32181
      KAFKA_CFG_LISTENERS=PLAINTEXT://: 9092
      KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost: 9092
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      ALLOW_ANONYMOUS_LOGIN: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper: 32181
      KAFKA_CFG_LISTENERS=PLAINTEXT://: 9093
      KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost: 9093
      ALLOW_PLAINTEXT_LISTENER: yes
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092,kafka-2:29093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:32181